# this is a script that uses the output of FastOrthallprot.py and gives you a fasta amino acid file with all the proteins not in the FastOrtho anaylis but in the Bakta annotation

def main():
    # Load protein IDs from a .txt file generated by FastOrthallprot.py
    with open('PMC-all-orthoprot.txt', 'r') as file:
        protein_ids = set(file.read().splitlines())

    # open the Bakata annotation change the name here
    with open('Peltigera_membranacea_cyanobiont.faa', 'r') as input_faa:
        # Open the output .faa file to append sequences
        with open('PMC-nonFO-prot.faa', 'a') as output_faa: # change the name here for the species of interest
            sequence = ''
            write_sequence = False

            for line in input_faa:
                if line.startswith('>'):
                    # Check if the previous sequence should be written to the output file
                    if write_sequence:
                        output_faa.write(sequence)

                    # Reset sequence and determine if the current sequence should be written
                    sequence = line
                    protein_id = line.split()[0].lstrip('>')
                    write_sequence = protein_id not in protein_ids
                else:
                    sequence += line

            # Check and write the last sequence after the loop ends
            if write_sequence:
                output_faa.write(sequence)

if __name__ == '__main__':
    main()
